# Generated by Django 2.2.7 on 2020-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Central'), (3, 'Repartidor'), (4, 'Administrador')], default=1, null=True),
        ),
    ]
