# Generated by Django 2.2.7 on 2020-05-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200524_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
