# Generated by Django 2.2.7 on 2020-08-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200723_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Central'), (3, 'Repartidor'), (4, 'Administrador'), (5, 'Comerciante')], default=1, null=True),
        ),
    ]
