# Generated by Django 2.2.7 on 2020-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200901_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Central'), (3, 'Repartidor'), (4, 'Administrador'), (5, 'Comerciante'), (6, 'Mercadologo')], default=1, null=True),
        ),
    ]
