# Generated by Django 2.2.7 on 2020-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200906_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='merchant_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
