# Generated by Django 2.2.7 on 2020-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200912_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Central'), (3, 'Repartidor'), (4, 'Administrador'), (5, 'Comerciante'), (6, 'Mercadologo'), (7, 'Sucursal')], default=1, null=True),
        ),
    ]
