# Generated by Django 2.2.7 on 2020-06-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0006_auto_20200601_1948'),
        ('common', '0003_orderstatus'),
        ('delivery_men', '0004_deliveryman_location'),
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('service_price', models.FloatField()),
                ('indications', models.TextField()),
                ('approximate_price_order', models.FloatField()),
                ('date_delivered_order', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=15, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery_men.DeliveryMan')),
                ('from_address_id', models.ForeignKey(blank=True, help_text='Place of purchase or place of delivery depending on the service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_address', to='customers.CustomerAddress')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.OrderStatus')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Service')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
                ('to_address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_address', to='customers.CustomerAddress')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=60)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='orders/pictures/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'orders_order_detail',
            },
        ),
    ]
