# Generated by Django 2.2.7 on 2020-07-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('customers', '0001_initial'),
        ('delivery_men', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRejectedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reason_rejection', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders_history_rejected_orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('service_price', models.FloatField()),
                ('indications', models.TextField(blank=True, null=True)),
                ('approximate_price_order', models.CharField(max_length=30)),
                ('date_delivered_order', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=15, null=True)),
                ('reason_rejection', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum_response_time', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('distance', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('delivery_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_man', to='delivery_men.DeliveryMan')),
                ('from_address', models.ForeignKey(blank=True, help_text='Place of purchase or place of delivery depending on the service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_address', to='customers.CustomerAddress')),
                ('order_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.OrderStatus')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='orders/pictures/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.Order')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'orders_order_detail',
            },
        ),
    ]
