# Generated by Django 2.2.7 on 2020-07-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('common', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Station'),
        ),
        migrations.AddField(
            model_name='order',
            name='station_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_service', to='stations.StationService'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_address', to='customers.CustomerAddress'),
        ),
    ]
