# Generated by Django 2.2.7 on 2020-06-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200604_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='indications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.OrderStatus'),
        ),
    ]
