# Generated by Django 2.2.7 on 2020-07-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_men', '0003_deliveryman_user'),
        ('common', '0002_notification_user'),
        ('orders', '0002_auto_20200704_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historyrejectedorders',
            name='delivery_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_men.DeliveryMan'),
        ),
        migrations.AddField(
            model_name='historyrejectedorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='historyrejectedorders',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status'),
        ),
    ]
