# Generated by Django 2.2.7 on 2020-07-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200704_1155'),
        ('orders', '0003_auto_20200704_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Service'),
            preserve_default=False,
        ),
    ]
