# Generated by Django 2.2.7 on 2020-07-12 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 18, 38, 53, 936335, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
