# Generated by Django 2.2.7 on 2020-06-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200605_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_man_id',
            new_name='delivery_man',
        ),
    ]
