# Generated by Django 2.2.7 on 2020-06-14 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200605_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='maximum_response_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 22, 7, 42, 58493, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
