# Generated by Django 2.2.7 on 2020-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200712_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='validate_qr',
            field=models.BooleanField(default=False),
        ),
    ]
