# Generated by Django 2.2.7 on 2020-06-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20200601_1948'),
        ('orders', '0006_order_maximum_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='station_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_service', to='stations.StationService'),
            preserve_default=False,
        ),
    ]
