# Generated by Django 2.2.7 on 2020-07-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200704_1101'),
        ('orders', '0007_ratingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member_station',
            field=models.ForeignKey(blank=True, help_text='For update statistics member station', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_station', to='stations.MemberStation'),
        ),
    ]
