# Generated by Django 2.2.7 on 2020-06-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0005_deliveryman_delivery_status'),
        ('common', '0007_deliverymanstatus'),
        ('orders', '0007_auto_20200616_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='HistoryRejectedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reason_rejecting', models.CharField(max_length=100)),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_men.DeliveryMan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'orders_history_rejected_orders',
            },
        ),
    ]
