# Generated by Django 2.2.7 on 2020-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200617_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrejectedorders',
            name='reason_rejecting',
        ),
        migrations.AddField(
            model_name='historyrejectedorders',
            name='reason_rejection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
