# Generated by Django 2.2.7 on 2020-06-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200617_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approximate_price_order',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.Order'),
        ),
    ]
