# Generated by Django 2.2.7 on 2020-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200620_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='2384080578', max_length=15),
            preserve_default=False,
        ),
    ]
