# Generated by Django 2.2.7 on 2020-08-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200814_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approximate_price_order',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
