# Generated by Django 2.2.7 on 2020-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200815_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
