# Generated by Django 2.2.7 on 2020-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason_rejection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
