# Generated by Django 2.2.7 on 2020-07-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
    ]
