# Generated by Django 2.2.7 on 2020-08-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200818_0017'),
        ('merchants', '0008_auto_20200823_1129'),
        ('orders', '0013_auto_20200816_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='have_menu_options',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderDetailMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_menu', models.CharField(max_length=100)),
                ('name_option', models.CharField(max_length=100)),
                ('price_option', models.FloatField(blank=True, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_options', to='orders.OrderDetail')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_menu_category', to='merchants.ProductMenuCategory')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_menu_option', to='merchants.ProductMenuOption')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'orders_order_detail_menu',
            },
        ),
    ]
