# Generated by Django 2.2.7 on 2020-08-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200824_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailmenu',
            name='price_option',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
