# Generated by Django 2.2.7 on 2020-08-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200825_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailmenu',
            old_name='name_menu',
            new_name='menu_name',
        ),
        migrations.RenameField(
            model_name='orderdetailmenuoption',
            old_name='name_option',
            new_name='option_name',
        ),
    ]
