# Generated by Django 2.2.7 on 2020-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200825_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmenu',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
