# Generated by Django 2.2.7 on 2020-09-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200902_1342'),
        ('orders', '0019_auto_20200901_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.CustomerPromotion'),
        ),
    ]
