# Generated by Django 2.2.7 on 2020-09-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ready_date',
            field=models.DateTimeField(blank=True, help_text='When the order is ready', null=True),
        ),
    ]
