# Generated by Django 2.2.7 on 2020-09-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0021_merchant_total_grades'),
        ('orders', '0021_order_order_ready_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingorder',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='ratingorder',
            name='rating_merchant',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ratingorder',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
