# Generated by Django 2.2.7 on 2020-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200922_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_update_order',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
