# Generated by Django 2.2.7 on 2020-12-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20201208_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card_id',
            new_name='card',
        ),
    ]
