# Generated by Django 2.2.7 on 2020-12-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20201208_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmenuoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
