# Generated by Django 2.2.7 on 2021-01-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orderdetailmenuoption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_rate_operating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='increment_price_operating',
            field=models.FloatField(default=0),
        ),
    ]
