# Generated by Django 2.2.7 on 2020-12-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='conekta_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
