# Generated by Django 2.2.7 on 2020-06-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_typeaddress'),
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='type_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.TypeAddress'),
            preserve_default=False,
        ),
    ]
