# Generated by Django 2.2.7 on 2020-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='exterior_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='full_address',
            field=models.CharField(max_length=350),
        ),
    ]
