# Generated by Django 2.2.7 on 2020-07-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200720_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_safe_user',
            field=models.BooleanField(default=False),
        ),
    ]
