# Generated by Django 2.2.7 on 2020-06-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200604_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='type_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.TypeAddress'),
        ),
    ]
