# Generated by Django 2.2.7 on 2020-07-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200624_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='full_address',
            field=models.CharField(default='Avenida insurgentes sur', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='references',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='suburb',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
