# Generated by Django 2.2.7 on 2020-08-30 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200818_0017'),
        ('customers', '0006_auto_20200801_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code_share',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='code_used_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoryCustomerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Code the customer issued by', max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('is_pending', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(help_text='Customer that is providing the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to='customers.Customer')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
                ('used_by', models.ForeignKey(help_text='User that used the code to order', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
            options={
                'db_table': 'customers_customer_history_invitation',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.HistoryCustomerInvitation')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'customers_customer_invitation',
            },
        ),
    ]
