# Generated by Django 2.2.7 on 2020-09-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200830_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='historycustomerinvitation',
            name='used_used_by',
            field=models.BooleanField(default=False, help_text='Already used by use enter code promo'),
        ),
    ]
