# Generated by Django 2.2.7 on 2020-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20200901_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpromotion',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customerpromotion',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
