# Generated by Django 2.2.7 on 2020-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200902_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
