# Generated by Django 2.2.7 on 2020-09-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20200906_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historycustomerinvitation',
            name='code',
            field=models.CharField(help_text='Code the customer issued by', max_length=50),
        ),
    ]
