# Generated by Django 2.2.7 on 2020-12-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20201008_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
