# Generated by Django 2.2.7 on 2020-05-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(max_length=80)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='stations/pictures/')),
                ('station_name', models.CharField(max_length=100)),
                ('station_verified', models.BooleanField(default=False)),
                ('document_verified', models.FileField(upload_to='stations/documents/')),
                ('assign_delivery_manually', models.BooleanField(default=False)),
                ('cancellation_policies', models.TextField(blank=True, null=True)),
                ('reputation', models.FloatField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('total_delivery_man', models.PositiveIntegerField(default=0)),
                ('total_messages_support', models.PositiveIntegerField(default=0)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('plate', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
