# Generated by Django 2.2.7 on 2020-07-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_notification_user'),
        ('customers', '0002_customer_user'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberstation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='memberstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
        migrations.AddField(
            model_name='memberstation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status'),
        ),
        migrations.AlterUniqueTogether(
            name='stationservice',
            unique_together={('station', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='stationschedule',
            unique_together={('station', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='memberstation',
            unique_together={('station', 'customer')},
        ),
    ]
