# Generated by Django 2.2.7 on 2020-05-28 00:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_schedule_service'),
        ('stations', '0002_station_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='information_is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('base_rate_price', models.FloatField()),
                ('price_kilometer', models.FloatField()),
                ('from_kilometer', models.FloatField()),
                ('to_kilometer', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Service')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Schedule')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationPhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=10)),
                ('exterior_number', models.CharField(max_length=10)),
                ('inside_number', models.CharField(blank=True, max_length=10, null=True)),
                ('references', models.CharField(max_length=150)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
