# Generated by Django 2.2.7 on 2020-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20200527_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='allow_cancellations',
            field=models.BooleanField(default=True),
        ),
    ]
