# Generated by Django 2.2.7 on 2020-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_station_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='quantity_safe_order',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
