# Generated by Django 2.2.7 on 2020-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_station_quantity_safe_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='free_orders_activated',
            field=models.BooleanField(default=False),
        ),
    ]
