# Generated by Django 2.2.7 on 2020-06-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_schedule_service'),
        ('stations', '0005_remove_stationaddress_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stationservice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='stationschedule',
            unique_together={('station', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='stationservice',
            unique_together={('station', 'service')},
        ),
    ]
