# Generated by Django 2.2.7 on 2020-07-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_station_free_orders_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='from_hour_free_order',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='to_hour_free_order',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
