# Generated by Django 2.2.7 on 2020-06-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200624_1200'),
        ('customers', '0006_auto_20200624_1200'),
        ('stations', '0006_auto_20200601_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_date', models.DateTimeField(auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_orders_cancelled', models.PositiveIntegerField(default=0)),
                ('last_order_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'stations_member_station',
                'unique_together': {('station', 'customer')},
            },
        ),
    ]
