# Generated by Django 2.2.7 on 2020-09-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20200729_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='stationaddress',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='stationphonenumbers',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
