# Generated by Django 2.2.7 on 2020-10-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_area_zone'),
        ('stations', '0007_auto_20200901_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Area'),
        ),
    ]
