# Generated by Django 2.2.7 on 2020-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_memberstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstation',
            name='first_order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
