# Generated by Django 2.2.7 on 2020-07-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_typevehicle'),
        ('stations', '0009_auto_20200703_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.TypeVehicle'),
        ),
    ]
