# Generated by Django 2.2.7 on 2020-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_auto_20201110_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationzone',
            name='has_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationzone',
            name='has_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
