# Generated by Django 2.2.7 on 2020-11-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_auto_20201111_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='restricted_zones_activated',
            field=models.BooleanField(default=False),
        ),
    ]
