# Generated by Django 2.2.7 on 2020-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_station_restricted_zones_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='close_to',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='station',
            name='open_to',
            field=models.TimeField(default='10:00'),
        ),
    ]
