# Generated by Django 2.2.7 on 2021-01-01 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0012_auto_20201119_1458'),
        ('common', '0018_auto_20201231_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_men', '0009_auto_20201107_2255'),
        ('customers', '0014_customer_total_orders'),
        ('orders', '0028_orderdetailmenuoption_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=15)),
                ('issue', models.CharField(max_length=80)),
                ('is_to_order', models.BooleanField(default=False)),
                ('is_to_help', models.BooleanField(default=False, help_text='Support between customer and station')),
                ('is_to_delivery_man', models.BooleanField(default=False, help_text='Support between customer and delivery man')),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('order_sku', models.CharField(blank=True, max_length=10, null=True)),
                ('order_details', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('delivery_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery_men.DeliveryMan')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Station')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('receiver_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_by', to=settings.AUTH_USER_MODEL)),
                ('sender_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.Support')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='support',
            name='support_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.SupportStatus'),
        ),
        migrations.AddField(
            model_name='support',
            name='support_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.SupportType'),
        ),
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
