# Generated by Django 2.2.7 on 2021-01-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20210102_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supports', to='orders.Order'),
        ),
    ]
