# Generated by Django 2.2.7 on 2020-06-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_typeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='type_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Service'),
            preserve_default=False,
        ),
    ]
