# Generated by Django 2.2.7 on 2020-06-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_orderstatus_type_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='slug_name',
            field=models.CharField(max_length=40),
        ),
    ]
