# Generated by Django 2.2.7 on 2020-06-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200605_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryManStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug_name', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'common_delivery_man_status',
            },
        ),
    ]
