# Generated by Django 2.2.7 on 2020-08-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200813_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymerchant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='common.CategoryMerchant'),
        ),
    ]
