# Generated by Django 2.2.7 on 2020-06-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_deliverymanstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'get_latest_by': 'created', 'ordering': ['id']},
        ),
    ]
