# Generated by Django 2.2.7 on 2020-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200815_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymerchant',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorymerchant',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
