# Generated by Django 2.2.7 on 2020-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200901_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='build_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
