# Generated by Django 2.2.7 on 2020-07-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_notification_typenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
