# Generated by Django 2.2.7 on 2020-10-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20201008_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
