# Generated by Django 2.2.7 on 2020-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
