# Generated by Django 2.2.7 on 2020-05-18 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='customers/pictures/'),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(max_length=80)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='stations/pictures/')),
                ('station_name', models.CharField(max_length=100)),
                ('station_verified', models.BooleanField(default=False)),
                ('document_verified', models.FileField(upload_to='stations/documents/')),
                ('assign_delivery_manually', models.BooleanField()),
                ('cancellation_policies', models.TextField()),
                ('reputation', models.FloatField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('total_delivery_man', models.PositiveIntegerField(default=0)),
                ('total_messages_support', models.PositiveIntegerField(default=0)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
