# Generated by Django 2.2.7 on 2020-05-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0002_auto_20200518_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merchant',
            new_name='Station',
        ),
    ]
