# Generated by Django 2.2.7 on 2020-05-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200518_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='assign_delivery_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='cancellation_policies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
