# Generated by Django 2.2.7 on 2021-02-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantpromotionhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchantpromotiontype',
            options={},
        ),
        migrations.AlterModelTable(
            name='merchantpromotion',
            table='merchant_promotions',
        ),
        migrations.AlterModelTable(
            name='merchantpromotionhistory',
            table='merchant_promotions_history',
        ),
        migrations.AlterModelTable(
            name='merchantpromotiontype',
            table='merchant_promotion_type',
        ),
    ]
