# Generated by Django 2.2.7 on 2021-02-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210206_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpromotion',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='promotions', to='merchants.Merchant'),
        ),
        migrations.AlterField(
            model_name='merchantpromotionhistory',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='promotions.MerchantPromotion'),
        ),
        migrations.AlterField(
            model_name='merchantpromotiontimeinterval',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_intervals', to='promotions.MerchantPromotion'),
        ),
        migrations.AlterField(
            model_name='merchantpromotiontimescheduleinterval',
            name='promotion_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='promotions.MerchantPromotionTimeInterval'),
        ),
    ]
