# Generated by Django 2.2.7 on 2020-08-15 04:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='approximate_preparation_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
