# Generated by Django 2.2.7 on 2020-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_auto_20200814_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantaddress',
            name='full_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
