# Generated by Django 2.2.7 on 2020-08-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_auto_20200816_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='merchants.CategoryProducts'),
        ),
    ]
