# Generated by Django 2.2.7 on 2020-08-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200818_0017'),
        ('merchants', '0007_auto_20200818_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('is_obligatory', models.BooleanField()),
                ('min_options_choose', models.PositiveIntegerField()),
                ('max_options_choose', models.PositiveIntegerField()),
                ('ordering', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='ordering',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='have_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug_name', models.CharField(max_length=50)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=90)),
                ('price', models.FloatField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='merchants.ProductMenuCategory')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchants.TypeOption')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_categories', to='merchants.Product'),
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status'),
        ),
    ]
