# Generated by Django 2.2.7 on 2020-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_auto_20200823_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmenucategory',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='productmenuoption',
            name='type',
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='have_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='is_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='limit_options_choose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='max_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmenucategory',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
