# Generated by Django 2.2.7 on 2020-09-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
