# Generated by Django 2.2.7 on 2020-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_auto_20200902_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='rate',
            field=models.FloatField(default=2.0),
        ),
    ]
