# Generated by Django 2.2.7 on 2020-09-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0015_auto_20200908_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='rate',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='type_menu',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='merchants.TypeMenuMerchant'),
        ),
    ]
