# Generated by Django 2.2.7 on 2020-09-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0019_productmenuoption_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorysectionproducts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='merchants.CategoryProducts'),
        ),
    ]
