# Generated by Django 2.2.7 on 2020-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0020_subcategorysectionproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='total_grades',
            field=models.IntegerField(default=0),
        ),
    ]
