# Generated by Django 2.2.7 on 2020-09-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0021_merchant_total_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
