# Generated by Django 2.2.7 on 2020-09-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0022_merchant_full_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantschedule',
            options={'ordering': ['schedule_id']},
        ),
    ]
