# Generated by Django 2.2.7 on 2020-10-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_area_zone'),
        ('merchants', '0023_auto_20200927_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Area'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Zone'),
        ),
    ]
