# Generated by Django 2.2.7 on 2020-11-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_appversion_app'),
        ('merchants', '0027_auto_20201024_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='delivery_payment',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='from_price_pay_delivery',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_delivery_free',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='pay_delivery',
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MerchantDeliveryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('available_delivery', models.BooleanField(default=False, help_text='Si tiene el envio disponible')),
                ('is_traceable', models.BooleanField(default=False)),
                ('is_free_delivery', models.BooleanField(default=False)),
                ('is_manage_zones', models.BooleanField(default=False)),
                ('pay_delivery', models.BooleanField(default=False)),
                ('is_minimum_price_sale', models.BooleanField(default=False)),
                ('from_price_pay_delivery', models.FloatField(default=0)),
                ('delivery_payment', models.FloatField(default=0)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_rules', to='merchants.Merchant')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
