# Generated by Django 2.2.7 on 2020-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0028_auto_20201107_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantschedule',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
