# Generated by Django 2.2.7 on 2020-11-29 08:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0015_typezone'),
        ('merchants', '0030_auto_20201129_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('poly', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('base_rate_price', models.FloatField(blank=True, null=True)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('has_price', models.BooleanField(default=False)),
                ('has_schedule', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.TypeZone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
