# Generated by Django 2.2.7 on 2020-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0031_merchantzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='operational_zones_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='restricted_zones_activated',
            field=models.BooleanField(default=False),
        ),
    ]
