# Generated by Django 2.2.7 on 2020-12-05 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0032_auto_20201129_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_methods', to='merchants.Merchant')),
            ],
            options={
                'db_table': 'merchants_merchant_payment_method',
            },
        ),
    ]
