# Generated by Django 2.2.7 on 2020-12-05 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmethod'),
        ('merchants', '0033_merchantpaymentmethod'),
        ('common', '0015_typezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentmethod',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='merchantpaymentmethod',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status'),
        ),
    ]
