# Generated by Django 2.2.7 on 2020-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0034_auto_20201205_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='accept_payment_online',
            field=models.BooleanField(default=False),
        ),
    ]
