# Generated by Django 2.2.7 on 2020-12-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0035_merchant_accept_payment_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
