# Generated by Django 2.2.7 on 2020-12-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0037_auto_20201212_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmenuoption',
            name='quantity',
        ),
    ]
