# Generated by Django 2.2.7 on 2021-01-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0039_auto_20210103_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproducts',
            old_name='order',
            new_name='ordering',
        ),
    ]
