# Generated by Django 2.2.7 on 2021-01-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0040_auto_20210103_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproducts',
            options={'get_latest_by': 'created', 'ordering': ['-ordering', '-created']},
        ),
    ]
