# Generated by Django 2.2.7 on 2021-01-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0042_auto_20210103_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='has_rate_operating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='increment_price_operating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='merchantschedule',
            name='schedule_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
