# Generated by Django 2.2.7 on 2021-01-17 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20201231_1728'),
        ('merchants', '0044_merchanttag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttag',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Area'),
        ),
        migrations.AddField(
            model_name='merchanttag',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='merchants/tags/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
