# Generated by Django 2.2.7 on 2020-05-26 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe ser ingresado con el formato: +23856671672. Hasta 15 digitos permitidos', regex='\\+?1?\\d{9,15}$')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='customers/pictures/')),
                ('salary_per_order', models.FloatField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('reputation', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'delivery_men_delivery_man',
            },
        ),
    ]
