# Generated by Django 2.2.7 on 2020-07-04 16:01

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe ser ingresado con el formato: +23856671672. Hasta 15 digitos permitidos', regex='\\+?1?\\d{9,15}$')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='deliveryman/pictures/')),
                ('salary_per_order', models.FloatField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('reputation', models.FloatField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('delivery_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.DeliveryManStatus')),
            ],
            options={
                'db_table': 'delivery_men_delivery_man',
            },
        ),
        migrations.CreateModel(
            name='DeliveryManAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=10)),
                ('exterior_number', models.CharField(max_length=10)),
                ('inside_number', models.CharField(blank=True, max_length=10, null=True)),
                ('references', models.CharField(max_length=150)),
                ('delivery_man', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='delivery_men.DeliveryMan')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'delivery_man_address',
            },
        ),
    ]
