# Generated by Django 2.2.7 on 2020-05-22 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_men', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymen',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooter.apps.users.Station'),
        ),
        migrations.AddField(
            model_name='deliverymen',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='scooter.apps.common.Status'),
        ),
        migrations.AddField(
            model_name='deliverymen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
