# Generated by Django 2.2.7 on 2020-07-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200704_1101'),
        ('delivery_men', '0003_deliveryman_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Vehicle'),
        ),
    ]
