# Generated by Django 2.2.7 on 2020-05-28 05:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0003_deliveryman_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
