# Generated by Django 2.2.7 on 2020-06-14 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_deliverymanstatus'),
        ('delivery_men', '0004_deliveryman_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='delivery_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.DeliveryManStatus'),
        ),
    ]
