# Generated by Django 2.2.7 on 2020-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0004_deliveryman_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymanaddress',
            name='references',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
