# Generated by Django 2.2.7 on 2020-06-25 04:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0005_deliveryman_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
