# Generated by Django 2.2.7 on 2020-06-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200624_1200'),
        ('delivery_men', '0006_auto_20200624_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryManAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=10)),
                ('exterior_number', models.CharField(max_length=10)),
                ('inside_number', models.CharField(blank=True, max_length=10, null=True)),
                ('references', models.CharField(max_length=150)),
                ('delivery_man', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery_men.DeliveryMan')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Status')),
            ],
            options={
                'db_table': 'delivery_man_address',
            },
        ),
    ]
