# Generated by Django 2.2.7 on 2020-11-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0027_auto_20201024_1335'),
        ('delivery_men', '0006_auto_20200730_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='salary_per_order',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='from_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
    ]
