# Generated by Django 2.2.7 on 2020-07-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0007_deliverymanaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymanaddress',
            name='delivery_man',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='delivery_men.DeliveryMan'),
        ),
    ]
