# Generated by Django 2.2.7 on 2020-11-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_appversion_app'),
        ('delivery_men', '0007_auto_20201107_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='name',
            field=models.CharField(default='null', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.TypeVehicle'),
        ),
    ]
