# Generated by Django 2.2.7 on 2020-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0008_auto_20201107_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
