# Generated by Django 2.2.7 on 2020-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_men', '0008_auto_20200701_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='deliveryman/pictures/'),
        ),
    ]
